<?php
/**
 * @var Bss\RewardPoint\Block\Cart\SpendPoint
 */
//  @codingStandardsIgnoreFile
?>
<?php 
    $call_js = 'Bss_RewardPoint/js/spend_point';
    $url = $block->getUrl('rewardpoint/cart/updatePost');
    if ($block->isPagePayPalReview()) {
       $call_js = 'Bss_RewardPoint/js/spend_point_paypal_express_review';
       $url = $block->getUrl('rewardpoint/cart/updatePostPayPal');
    }
?>
<?php if ($block->getRewardPointsTotal() && $block->isDisplay()) : ?>
    <div class="block bss-reward-point"
        id="block-bss-reward-point"
        data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'
    >
        <?php if (!$block->isPagePayPalReview()): ?>
            <div class="loading"><img src="<?php echo $block->getViewFileUrl('Bss_RewardPoint::images/imgzoom-loading.gif'); ?>" /></div>
        <?php endif ?>
        <div class="title" data-role="title">
            <strong id="block-bss-reward-point-heading" role="heading" aria-level="2">
                <?php /* @noEscape */ echo __('Apply Reward') ?>
            </strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-bss-reward-point-heading">
            <div class="block-content">
                <span class="balance-price-label">
                    <span><?php /* @noEscape */ echo __('Your Reward Point:'); ?></span>
                    <span class="rewardpoint-total"><?php /* @noEscape */ echo $block->getRewardPointsTotal(); ?></span>
                </span>
            </div>
            <div class="block-content">
                <span class="rate-label">
                    <span><?php /* @noEscape */ echo __('%1 point(s) can be redeemed for ', $block->getRateCurrencytoPoint()); ?></span><span class="rewardpoint-current"><?php /* @noEscape */ echo __('%1',$block->getCurrency()); ?></span>
                </span>
            </div>
            <?php if ($block->isPointSlider()): ?>
                <div id="slider-point">
                    <div class="rangeinner"></div>
                    <div id="display-number-point-slider" class="ui-slider-handle"></div>
                </div>
            <?php endif ?>
            <form id="bss-reward-point-form"
                  action="<?= /* @noEscape */ $url ?>"
                  method="post"
                  data-mage-init='{"<?= /* @noEscape */ $call_js ?>":{}}'>
                <div class="fieldset bss-reward-point">
                    <input type="hidden" name="remove" id="remove-bss-reward-point" value="0" />
                    <div class="field">
                        <label for="bss-reward-point" class="label">
                            <span><?php /* @noEscape */ echo __('Enter Value') ?></span>
                        </label>
                        <div class="control">
                            <input type="number"
                                class="input-text validate-number validate-digits"
                                id="bss-reward-point-value"
                                name="spend_reward_point"
                                value="<?php /* @noEscape */ echo $block->getSpendPoints();?>"
                                max="<?php /* @noEscape */ echo $block->getPointBalance();?>"
                                placeholder="<?php /* @noEscape */ echo $block->escapeHtml(__('Enter Value'));?>" />
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button class="action bss-reward-point-apply primary"
                                type="button"
                                value="<?php /* @noEscape */ echo __('Apply Reward') ?>"
                            ><span><?php /* @noEscape */ echo __('Apply Reward') ?></span>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php endif; ?>
