<?php
/**
 * @var Bss\SocialLogin\Block\SocialLogin\EnableModule
 */
//  @codingStandardsIgnoreFile
?>
<?php if ($block->getTotal()->getValue()): ?>
    <tr class="rewardpoints">
        <th colspan="<?= /* @escapeNotVerified */ $block->getColspan() ?>" style="<?= /* @escapeNotVerified */ $block->getTotal()->getStyle() ?>" class="admin__total-mark" scope="row">
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?= /* @escapeNotVerified */ $block->getTotal()->getTitle() ?>
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
        </th>
        <td style="<?= /* @escapeNotVerified */ $block->getTotal()->getStyle() ?>" class="admin__total-amount"
            data-th="<?= $block->escapeHtml($block->getTotal()->getTitle()) ?>">
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?><strong><?php endif; ?>
                <?= /* @escapeNotVerified */ $block->getTotal()->getValue() ?>
            <?php if ($block->getRenderingArea() == $block->getTotal()->getArea()): ?></strong><?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
