<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
$row = $block->getArrayRows();
?>

<div class="design_theme_ua_regexp" id="grid<?= /* @escapeNotVerified */ $_htmlId ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" id="<?= /* @escapeNotVerified */ $block->getElement()->getId() ?>">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?= /* @escapeNotVerified */ $column['label'] ?></th>
                <?php endforeach;?>
            </tr>
            </thead>
            <!-- <tbody id="addRow<?= /* @escapeNotVerified */ $_htmlId ?>"></tbody> -->
            <tbody id="addRow<?= /* @escapeNotVerified */ $_htmlId ?>">
                <tr id="bss_maximum_earn_review">
                    <?php if(!empty($row)) : ?>
                        <td>
                            <select id="maximum_type_date" name="groups[earning_point][fields][maximum_earn_review][value][type_date]" class=" select admin__control-select">
                                <option value="day" <?= ($row['type_date'] == 'day')? 'selected':''; ?>><?= /* @escapeNotVerified */ __('Day') ?></option>
                                <option value="month" <?= ($row['type_date'] == 'month')? 'selected':''; ?>><?= /* @escapeNotVerified */ __('Month') ?></option>
                                <option value="year" <?= ($row['type_date'] == 'year')? 'selected':''; ?>><?= /* @escapeNotVerified */ __('Year') ?></option>
                            </select>
                        </td>
                        <td>
                            <input type="text" id="maximum_period_time" name="groups[earning_point][fields][maximum_earn_review][value][period_time]" value="<?= $row['period_time'] ?>" class="input-text validate-number validate-greater-than-zero">
                        </td>
                        <td>
                            <input type="text" id="maximum_point_review" name="groups[earning_point][fields][maximum_earn_review][value][maximum_point_review]" value="<?= $row['maximum_point_review'] ?>" class="input-text validate-number validate-greater-than-zero">
                        </td>
                    <?php else :?>
                        <td>
                            <select id="maximum_type_date" name="groups[earning_point][fields][maximum_earn_review][value][type_date]" class=" select admin__control-select">
                                <option value="day"><?= /* @escapeNotVerified */ __('Day') ?></option>
                                <option value="month"><?= /* @escapeNotVerified */ __('Month') ?></option>
                                <option value="year"><?= /* @escapeNotVerified */ __('Year') ?></option>
                            </select>
                        </td>
                        <td>
                            <input type="text" id="maximum_period_time" name="groups[earning_point][fields][maximum_earn_review][value][period_time]" value="" class="input-text validate-number validate-greater-than-zero">
                        </td>
                        <td>
                            <input type="text" id="maximum_point_review" name="groups[earning_point][fields][maximum_earn_review][value][maximum_point_review]" value="" class="input-text validate-number validate-greater-than-zero">
                        </td>
                    <?php endif;?>
                </tr>
            </tbody>
        </table>
    </div>
    <input type="hidden" name="groups[earning_point][fields][maximum_earn_review][value][__empty]" value="" />

    <script type="text/x-magento-init">
        {
            "*": {
                "Bss_RewardPoint/js/maximum_earn_review":{
                    <?php if ($block->getElement()->getDisabled()):?>
                        "disabled_element": "true",
                    <?php endif ?>
                    "htmlId": "<?= /* @escapeNotVerified */ $_htmlId; ?>"
                }
            }
        }
    </script>
</div>
