<?php
/**
 * @var Bss\RewardPoint\Block\Customer\RewardPoint
 */
//  @codingStandardsIgnoreFile
?>
<?php
$balance_info = $block->getBalanceInfo();
$point_balance = $balance_info? $balance_info->getPointBalance() : '';
$point_earned = $balance_info? $balance_info->getPointEarned() : '';
$point_spent = $balance_info? $balance_info->getPointSpent() : '';
$transactions = $block->getTransactions();
$count = count($transactions);
?>
<div class="block block-balance">
    <div class="block-title">
        <b><?= $block->escapeHtml(__('Balance infomation')) ?></b>
    </div>
    <div class="block-content">
        <p class="rw-point">
            <span><?= $block->escapeHtml(__('Points balance')) ?>:</span>
            <span class="panel-point"><?= $point_balance ?></span>
        </p>
        <p class="rw-point">
            <span><?= $block->escapeHtml(__('Total earned')) ?>:</span>
            <span class="panel-point"><?= $point_earned ?></span>
        </p>
        <p class="rw-point">
            <span><?= $block->escapeHtml(__('Total spent')) ?>:</span>
            <span class="panel-point"><?= $point_spent ?></span>
        </p>
    </div>
</div>
<div class="block block-rate">
    <div class="block-title">
        <b><?= $block->escapeHtml(__('Exchange Rate')) ?></b>
    </div>
    <div class="block-content">
        <p class="rw-point">
            <span><?php /* @noEscape */ echo __('%1 point(s) can be redeemed for ', $block->getRateCurrencytoPoint()); ?></span><span class="panel-point"><?php /* @noEscape */ echo __($block->getCurrency()); ?></span>
        </p>
    </div>
</div>
<div class="block block-transaction">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('Transactions')) ?></strong>
        <?php if ($count > 0): ?>
            <a class="action view" href="<?= /* @escapeNotVerified */ $block->getUrl('rewardpoint/transaction') ?>">
                <span class="view-all"><?= /* @escapeNotVerified */ __('View All') ?></span>
            </a>
        <?php endif; ?>
    </div>
    <div class="block-content">
        <?php if ($count > 0): ?>
            <div class="table-wrapper transaction-recent">
                <table class="data table table-transaction-items recent" id="my-transactions-table">
                    <caption class="table-caption"><?= /* @escapeNotVerified */ __('Recent Transactions') ?></caption>
                    <thead>
                        <tr>
                            <th scope="col" class="col point"><?= /* @escapeNotVerified */ __('Point') ?></th>
                            <th scope="col" class="col balance"><?= /* @escapeNotVerified */ __('Balance') ?></th>
                            <th scope="col" class="col note"><?= /* @escapeNotVerified */ __('Note') ?></th>
                            <th scope="col" class="col created_by"><?= /* @escapeNotVerified */ __('Created by') ?></th>
                            <th scope="col" class="col type"><?= /* @escapeNotVerified */ __('Transaction type') ?></th>
                            <th scope="col" class="col create_at"><?= /* @escapeNotVerified */ __('Transaction date') ?></th>
                            <th scope="col" class="col expires_at"><?= /* @escapeNotVerified */ __('Expiry date') ?></th>
                            <th scope="col" class="col action"><?= /* @escapeNotVerified */ __('Action') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($transactions as $transaction): ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtml(__('Point')) ?>" class="col point"><?= /* @escapeNotVerified */ $transaction->getPoint() ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Balance')) ?>" class="col balance"><?= /* @escapeNotVerified */ $block->getBalanceByTransaction($transaction->getId()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Note')) ?>" class="col note"><?= $block->escapeHtml($transaction->getNote()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Created by')) ?>" class="col created_by"><?= /* @escapeNotVerified */ $transaction->getCreatedBy() ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Transaction type')) ?>" class="col type"><?= /* @escapeNotVerified */ $block->getActionsName($transaction->getAction()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Transaction date')) ?>" class="col create_at"><?= /* @escapeNotVerified */ $block->formatDate($transaction->getCreatedAt()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Expiry date')) ?>" class="col expires_at"><?= /* @escapeNotVerified */ $block->formatDate($transaction->getExpiresAt()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                    <a href="<?= /* @escapeNotVerified */ $this->getUrl('rewardpoint/transaction/index', ['id' => $transaction->getId()]) ?>" class="action view">
                                        <span class="panel-point"><?= /* @escapeNotVerified */ __('View') ?></span>
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty"><span><?= /* @escapeNotVerified */ __('You have placed no transactions.') ?></span></div>
        <?php endif; ?>
    </div>
</div>
<?php
    $notify = $block->getNotify();
?>
<div class="block block-notify">
    <div class="block-title">
        <b><?= $block->escapeHtml(__('Notification')) ?></b>
    </div>
    <div class="block-content">
        <form action="<?= $this->getUrl('rewardpoint/notify/') ?>" method="post" id="rewardpoint-notify">
            <fieldset class="fieldset">
                <div class="field choice set notify_balance">
                    <label class="main-check-point" for="rwp_notify_balance">
                        <?= $block->escapeHtml(__('Notify when balance is updated')) ?>
                    <?php if ($notify->getId()): ?>
                        <input type="checkbox" id="rwp_notify_balance" name="notify_balance" class="checkbox" <?php if ($notify->getNotifyBalance()): ?>checked="checked"<?php endif ?>>
                    <?php else: ?>
                        <input type="checkbox" id="rwp_notify_balance" name="notify_balance" class="checkbox">
                    <?php endif ?>
                        <span class="geekmark"></span>
                    </label>
                </div>

                <div class="field choice set notify_expiration">
                    <label class="main-check-point" for="rwp_notify_expiration">
                        <?= $block->escapeHtml(__('Notify before expiration')) ?>
                    <?php if ($notify->getId()): ?>
                        <input type="checkbox" id="rwp_notify_expiration" name="notify_expiration" class="checkbox" <?php if ($notify->getNotifyExpiration()): ?>checked="checked"<?php endif ?>>
                    <?php else: ?>
                        <input type="checkbox" id="rwp_notify_expiration" name="notify_expiration" class="checkbox">
                    <?php endif ?>
                        <span class="geekmark"></span>
                    </label>
                </div>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action save primary" data-action="save-notify" title="<?= $block->escapeHtml(__('Save notify')) ?>">
                        <span><?= $block->escapeHtml(__('Save')) ?></span>
                    </button>
                </div>
            </div>
            <input type="hidden" name="customer_id" value="<?= $block->getCustomerId() ?>">
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#rewardpoint-notify": {
            "Bss_RewardPoint/js/notify": {}
        }
    }
</script>
